### ISSUE TITLE
Sentieon-docker repo and sentieon-amazon-omics docker repo merged

### ISSUE THREAD

**Issue by golharam** [Sentieon/sentieon-docker#2]
We are trying to use a single Docker image across all workflow engines (Omics and local CWL runner among others) and would love to see a single version of the sentieon docker image that we can use regardless of where we run workflows.  This would make it easier to manage and deploy rather than having to custom build/switch images based on workflow engine we want to use.

Right now, I see this repo and I see https://github.com/Sentieon/sentieon-amazon-omics.  The docker files don't look the same.

**Comment by DonFreed** [comment]
Thanks for the suggestion. This repository aims to host a fairly basic example dockerfile without many additional components. The Amazon HealthOmics [dockerfile](https://github.com/Sentieon/sentieon-amazon-omics/blob/master/container/sentieon_omics.dockerfile) aims to be a more complete dockerfile for AHO workflows.

We won't directly support a single version for all environments due to the diversity of different execution environments.
